### PR TITLE
Handling demo red ball in gazebo

### PR DESCRIPTION
**Pull request by vvasco**
This PR updates `demoRedBall` and `pf3dTracker` conf files to handle the red ball demo within `gazebo`.
More specifically:

### pf3dTracker
The following files have been added:
- `red_ball_gazebo.bmp` and `redball-gazebo.csv` model to deal with `gazebo` red ball's color and shape respectively;
- `pf3dTracker-gazebo.ini` that loads the previous files.

### demoRedBall
The following changes have been made:
- the `simulation` flag allows to run the demo in simulation;
- the `respond` method contains three new commands:
    - `start`: to start the demo;
    - `stop`: to stop the demo;
    - `update_pose x y z`: to update the ball position; 
    
    _Note: the behavior of the demo on the real robot has not changed and it automatically starts when running the module._

- added a gazebo folder with the ball model and gazebo world;

Also, a `demoRedBall_gazebo.xml.template` including the required modules and the related conf files is available.
The `demoRedBall` documentation has also been updated.

Here is an example of the demo running in `gazebo`:

https://user-images.githubusercontent.com/9716288/107494545-36ded280-6b8f-11eb-917f-8b4c0ff28dcd.mp4

Finally, these changes have also been successfully tested on `iCubErzelli02 ` to be sure that the demo on the real robot is not affected.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Fantastic addition @vvasco 🚀 

I've only a comment to make: can we consider updating the test introduced in https://github.com/robotology/icub-tests/pull/24 as well?

Actually, that test was meant for checking at least part of the pipeline.
We should merge the pathways.

Is this addition meant for testing or is it a general feature?

**Comment by vvasco** [comment]
I've had a quick look at the test and I think we can easily merge the simulation pathway.
The addition is meant to be a general feature, but it might be also useful for testing purposes.

**Comment by pattacini** [comment]
> I think we can easily merge the simulation pathway.

Thanks 👍🏻

**Review by pattacini — CHANGES_REQUESTED** [review]
CI is failing under Windows because GAZEBO is not found.
Perhaps, it'd be worth adding the CMake logic to deal with this condition.

**Comment by vvasco** [comment]
The CMake logic is there but by default the `GAZEBO_AVAILABLE` option is set to `ON`. I can set this to be `OFF` instead by default.

**Comment by pattacini** [comment]
> The CMake logic is there but by default the `GAZEBO_AVAILABLE` option is set to `ON`. I can set this to be `OFF` instead by default.

Uhm, GAZEBO_AVAILABLE should be the result the check.

**Comment by pattacini** [comment]
In a nutshell `find_package(GAZEBO)` shouldn't have the REQUIRED option enabled; rather, you check whether it is available by reading GAZEBO_FOUND as the result of the `find_package` macro.

**Review by vtikha — APPROVED** [review]
LGTM 🎉🎉🎉

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
Waiting for the CI to complete and then I'll merge the PR!

**Comment by pattacini** [comment]
Apparently, we do still have problems:

```console
2021-04-20T16:22:55.1630643Z D:\a\icub-basic-demos\icub-basic-demos\demoRedBall\src\main.cpp(2048,18): error C2065: 'simulation': undeclared identifier [D:\a\icub-basic-demos\icub-basic-demos\build\demoRedBall\demoRedBall.vcxproj]
```

**Review by pattacini — CHANGES_REQUESTED** [review]
Apparently, we do still have problems:

```console
2021-04-20T16:22:55.1630643Z D:\a\icub-basic-demos\icub-basic-demos\demoRedBall\src\main.cpp(2048,18): error C2065: 'simulation': undeclared identifier [D:\a\icub-basic-demos\icub-basic-demos\build\demoRedBall\demoRedBall.vcxproj]
```

**Comment by vvasco** [comment]
There was a leftover, I fixed it.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
