### PR TITLE
Make pf3dBottomup OpenCV3-friendly

### PR DESCRIPTION
**Pull request by gsaponaro**
This makes pf3dBottomup compile with OpenCV 3 in Linux, porting some changes done in 2013 by OpenCV in commit https://github.com/Itseez/opencv/commit/06f4a56469836c443bfcc929d294822bb93e3aa3
- use modern OpenCV headers
- use void instead of CvStatus and values CV_OK, CV_NO_ERR (which according to the old header cxmisc.h were both equal to 0)
- remove call to cvGetMatSize
- use template function saturate_cast<> to convert between primitive types instead of old macro CV_CAST_8U
- do not use IPPI_CALL macros, as modern versions of OpenCV automatically use accelerators if available on the host platform, as per OpenCV Transparent API

Addresses #7

### CODE REVIEW

**Comment by gsaponaro** [comment]
Hi @pattacini, can you test this on Windows?

**Comment by pattacini** [comment]
Thanks a lot!
Merging anyway and then testing.
Stay tuned.

**Comment by pattacini** [comment]
It compiles gracefully!

**Comment by gsaponaro** [comment]
Good to know. :)

**Comment by gsaponaro** [comment]
Hi @martimbrandao, the above are some small updates to your bottom-up detector module, for compatibility with new OpenCV versions. I did not test the changes thoroughly, as nowadays we are not using the module anymore in demos - perhaps something we can try the next time you pass by the lab. Ciao!

**Comment by martimbrandao** [comment]
Thank you Giovanni!

**Pull request merged**
