### PR TITLE
Removed SearchMonitor

### LINKED ISSUE #45: Compilation failure with yarp 3.10
In https://github.com/robotology/robotology-superbuild/pull/1547#issuecomment-2259271460 we found some compilation failures of icub-basic-demos with YARP master branch of August 2024 (future YARP 3.10):

~~~
2024-07-30T18:19:34.1539372Z [3/28] Building CXX object demoRedBall/CMakeFiles/demoRedBall.dir/src/main.cpp.o
2024-07-30T18:19:34.1540196Z FAILED: demoRedBall/CMakeFiles/demoRedBall.dir/src/main.cpp.o 
2024-07-30T18:19:34.1543597Z /usr/bin/c++ -DBOOST_TEST_DYN_LINK -DLIBBULLET_VERSION=3.05 -DLIBBULLET_VERSION_GT_282 -D_USE_MATH_DEFINES -isystem /home/runner/work/robotology-superbuild/robotology-superbuild/build/install/include -O3 -DNDEBUG -std=c++17 -MD -MT demoRedBall/CMakeFiles/demoRedBall.dir/src/main.cpp.o -MF demoRedBall/CMakeFiles/demoRedBall.dir/src/main.cpp.o.d -o demoRedBall/CMakeFiles/demoRedBall.dir/src/main.cpp.o -c /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp
2024-07-30T18:19:34.1548611Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp: In member function ‘virtual bool managerThread::threadInit()’:
2024-07-30T18:19:34.1551216Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1533:18: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1552864Z  1533 |         bGeneral.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1553374Z       |                  ^~~~~~~~~~
2024-07-30T18:19:34.1555337Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1533:32: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1556797Z  1533 |         bGeneral.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1557286Z       |                                ^~~~~~~~~~
2024-07-30T18:19:34.1559032Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1554:16: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1560430Z  1554 |         bTorso.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1560896Z       |                ^~~~~~~~~~
2024-07-30T18:19:34.1562674Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1554:30: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1564084Z  1554 |         bTorso.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1564588Z       |                              ^~~~~~~~~~
2024-07-30T18:19:34.1566328Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1566:18: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1567732Z  1566 |         bLeftArm.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1568465Z       |                  ^~~~~~~~~~
2024-07-30T18:19:34.1570237Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1566:32: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1571693Z  1566 |         bLeftArm.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1572170Z       |                                ^~~~~~~~~~
2024-07-30T18:19:34.1573897Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1567:19: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1575311Z  1567 |         bRightArm.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1575793Z       |                   ^~~~~~~~~~
2024-07-30T18:19:34.1577556Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1567:33: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1579249Z  1567 |         bRightArm.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1579756Z       |                                 ^~~~~~~~~~
2024-07-30T18:19:34.1581500Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1587:15: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1582911Z  1587 |         bHome.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1583405Z       |               ^~~~~~~~~~
2024-07-30T18:19:34.1586637Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1587:29: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1587921Z  1587 |         bHome.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1588341Z       |                             ^~~~~~~~~~
2024-07-30T18:19:34.1589888Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1593:17: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1591093Z  1593 |         bArmSel.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1591507Z       |                 ^~~~~~~~~~
2024-07-30T18:19:34.1592967Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1593:31: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1594435Z  1593 |         bArmSel.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1594853Z       |                               ^~~~~~~~~~
2024-07-30T18:19:34.1596339Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1598:16: error: ‘class yarp::os::Bottle’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1597689Z  1598 |         bGrasp.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1598098Z       |                ^~~~~~~~~~
2024-07-30T18:19:34.1599584Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:1598:30: error: ‘class yarp::os::ResourceFinder’ has no member named ‘getMonitor’
2024-07-30T18:19:34.1600832Z  1598 |         bGrasp.setMonitor(rf.getMonitor());
2024-07-30T18:19:34.1601245Z       |                              ^~~~~~~~~~
2024-07-30T18:19:34.1602127Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp: At global scope:
2024-07-30T18:19:34.1603897Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2103:1: error: expected class-name before ‘{’ token
2024-07-30T18:19:34.1604939Z  2103 | {
2024-07-30T18:19:34.1605168Z       | ^
2024-07-30T18:19:34.1606285Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2109:23: error: ‘SearchReport’ does not name a type
2024-07-30T18:19:34.1607423Z  2109 |     void report(const SearchReport& report, const char *context)
2024-07-30T18:19:34.1608078Z       |                       ^~~~~~~~~~~~
2024-07-30T18:19:34.1609543Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp: In member function ‘void myReport::report(const int&, const char*)’:
2024-07-30T18:19:34.1611784Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2112:27: error: request for member ‘key’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1613041Z  2112 |         string key=report.key;
2024-07-30T18:19:34.1613398Z       |                           ^~~
2024-07-30T18:19:34.1614871Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2128:20: error: request for member ‘isFound’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1616131Z  2128 |         if (report.isFound)
2024-07-30T18:19:34.1616466Z       |                    ^~~~~~~
2024-07-30T18:19:34.1618123Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2129:35: error: request for member ‘value’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1619452Z  2129 |             actual.put(key,report.value);
2024-07-30T18:19:34.1619863Z       |                                   ^~~~~
2024-07-30T18:19:34.1621498Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2131:20: error: request for member ‘isComment’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1622813Z  2131 |         if (report.isComment==true)
2024-07-30T18:19:34.1623208Z       |                    ^~~~~~~~~
2024-07-30T18:19:34.1745412Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2133:36: error: request for member ‘value’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1747077Z  2133 |             comment.put(key,report.value);
2024-07-30T18:19:34.1747509Z       |                                    ^~~~~
2024-07-30T18:19:34.1749276Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2137:20: error: request for member ‘isDefault’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1750700Z  2137 |         if (report.isDefault==true)
2024-07-30T18:19:34.1751078Z       |                    ^~~~~~~~~
2024-07-30T18:19:34.1752614Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2139:37: error: request for member ‘value’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1754257Z  2139 |             fallback.put(key,report.value);
2024-07-30T18:19:34.1754681Z       |                                     ^~~~~
2024-07-30T18:19:34.1756196Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2147:28: error: request for member ‘isFound’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1757516Z  2147 |                 if (report.isFound)
2024-07-30T18:19:34.1757887Z       |                            ^~~~~~~
2024-07-30T18:19:34.1759385Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2149:44: error: request for member ‘value’ in ‘report’, which is of non-class type ‘const int’
2024-07-30T18:19:34.1760732Z  2149 |                     string hasValue=report.value;
2024-07-30T18:19:34.1761155Z       |                                            ^~~~~
2024-07-30T18:19:34.1762336Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp: In function ‘int main(int, char**)’:
2024-07-30T18:19:34.1764717Z /home/runner/work/robotology-superbuild/robotology-superbuild/src/icub-basic-demos/demoRedBall/src/main.cpp:2197:8: error: ‘class yarp::os::ResourceFinder’ has no member named ‘setMonitor’
2024-07-30T18:19:34.1766059Z  2197 |     rf.setMonitor(&rep);
2024-07-30T18:19:34.1766386Z       |        ^~~~~~~~~~
~~~

Probably (but I am not 100% sure) this is related to the change https://github.com/robotology/yarp/pull/3059, some other related issues and PRs:
* https://github.com/robotology/icub-main/issues/922
  * https://github.com/robotology/icub-main/pull/925
* https://github.com/robotology/yarp-devices-forcetorque/issues/40
  * https://github.com/robotology/yarp-devices-forcetorque/pull/41 
* https://github.com/robotology/wearables/issues/205
  * https://github.com/robotology/wearables/pull/206
* https://github.com/robotology/human-dynamics-estimation/issues/381 
  * https://github.com/robotology/human-dynamics-estimation/pull/382

### PR DESCRIPTION
**Pull request by randaz81**
A fix for https://github.com/robotology/icub-basic-demos/issues/45

### CODE REVIEW

**Comment by randaz81** [comment]
To be tested on a working setup

**Comment by pattacini** [comment]
At first sight, judging from the changes, we are losing a whole functionality.

**Comment by randaz81** [comment]
It's not clear to me if that code is manipulating config parameters (*), adding default values, or just printing help messages. Do you have a setup where it can be tested? 

(*) in this case some changes have be applied in the .ini file.

**Comment by pattacini** [comment]
I've no memory of that functionality: it was developed long long time ago.
Thus, I need to check it in-depth.

Probably, it may help to know how the functionalities offered by the methods getMonitor() / setMonitor() are remapped.

**Comment by pattacini** [comment]
>Do you have a setup where it can be tested?

Ideally, there's a dedicated test as suggested by @traversaro:
- https://github.com/robotology/icub-tests/pull/58#issuecomment-879617647

Need to check if it's still working though.

**Comment by traversaro** [comment]
> Need to check if it's still working though.

I am currently trying to do that, I will keep you posted.

**Comment by randaz81** [comment]
I'm still not 100% sure but I think that the only purpose of that code is to print the values read from the configuration file:
```
[INFO] Checking "robot": = icub (Getting robot name)
[INFO] Checking "left_arm": = on (Getting left arm use flag)
[INFO] Checking "right_arm": = on (Getting right arm use flag)
[INFO] Checking "torso": Getting torso use flag (default on)
[INFO] Checking "speech": = on (Getting speech use flag)
[INFO] Checking "use_network": = off (Getting network enable)
[INFO] Checking "simulation": = off (Getting simulation enable)
[INFO] Checking "traj_time": = 1.0 (Getting trajectory time)
[INFO] Checking "reach_tol": = 0.01 (Getting reaching tolerance)
[INFO] Checking "eye": = left (Getting the used eye)
[INFO] Checking "idle_tmo": = 5.0 (Getting idle timeout)
[INFO] Checking "thread_period": = 20 (Getting thread period [ms])
[INFO] Checking "pitch.min": = min -10.0 (Getting minimum value)
[INFO] Checking "pitch.min": = -10.0 (Getting minimum value)
[INFO] Checking "pitch.max": = max 10.0 (Getting maximum value)
[INFO] Checking "pitch.max": = 10.0 (Getting maximum value)
[INFO] Checking "roll.min": Getting minimum value
[INFO] Checking "roll.max": Getting maximum value
[INFO] Checking "yaw.min": Getting minimum value
[INFO] Checking "yaw.max": Getting maximum value
[INFO] Checking "grasp_enable": = on (Getting arm grasp mode)
[INFO] Checking "reach_offset": = reach_offset 0.0 -0.0500000000 ... (Getting reaching offset)
[INFO] Checking "reach_offset": = reach_offset 0.0 -0.0500000000 ... (Getting reaching offset)
[INFO] Checking "grasp_offset": = grasp_offset 0.0 0.0 0.0 (Getting grasping offset)
[INFO] Checking "grasp_offset": = grasp_offset 0.0 0.0 0.0 (Getting grasping offset)
[INFO] Checking "hand_orientation": = hand_orientation 0.0 -0.707106 ... (Getting hand orientation)
[INFO] Checking "hand_orientation": = hand_orientation 0.0 -0.707106 ... (Getting hand orientation)
[INFO] Checking "impedance_velocity_mode": = on (Getting arm impedance-velocity-mode)
[INFO] Checking "impedance_stiffness": = impedance_stiffness 0.40000000 ... (Getting joints stiffness)
[INFO] Checking "impedance_stiffness": = impedance_stiffness 0.40000000 ... (Getting joints stiffness)
[INFO] Checking "impedance_damping": = impedance_damping 0.002 0.002  ... (Getting joints damping)
[INFO] Checking "impedance_damping": = impedance_damping 0.002 0.002  ... (Getting joints damping)
[INFO] Checking "grasp_enable": = on (Getting arm grasp mode)
[INFO] Checking "reach_offset": = reach_offset 0.0 0.05000000000 ... (Getting reaching offset)
[INFO] Checking "reach_offset": = reach_offset 0.0 0.05000000000 ... (Getting reaching offset)
[INFO] Checking "grasp_offset": = grasp_offset 0.0 0.0 0.0 (Getting grasping offset)
[INFO] Checking "grasp_offset": = grasp_offset 0.0 0.0 0.0 (Getting grasping offset)
[INFO] Checking "hand_orientation": = hand_orientation 0.0 -0.707106 ... (Getting hand orientation)
[INFO] Checking "hand_orientation": = hand_orientation 0.0 -0.707106 ... (Getting hand orientation)
[INFO] Checking "impedance_velocity_mode": = on (Getting arm impedance-velocity-mode)
[INFO] Checking "impedance_stiffness": = impedance_stiffness 0.40000000 ... (Getting joints stiffness)
[INFO] Checking "impedance_stiffness": = impedance_stiffness 0.40000000 ... (Getting joints stiffness)
[INFO] Checking "impedance_damping": = impedance_damping 0.002 0.002  ... (Getting joints damping)
[INFO] Checking "impedance_damping": = impedance_damping 0.002 0.002  ... (Getting joints damping)
[INFO] Checking "poss": = poss -30.0 30.0 0.0 45.0 0.0 0 ... (Getting home poss)
[INFO] Checking "poss": = poss -30.0 30.0 0.0 45.0 0.0 0 ... (Getting home poss)
[INFO] Checking "vels": = vels 10.0 10.0 10.0 10.0 10.0  ... (Getting home vels)
[INFO] Checking "vels": = vels 10.0 10.0 10.0 10.0 10.0  ... (Getting home vels)
[INFO] Checking "hysteresis_thres": = 0.14999999999999999 (Getting hysteresis threshold)
[INFO] Checking "sphere_radius": = 0.050000000000000003 (Getting sphere radius)
[INFO] Checking "sphere_tmo": = 2.0 (Getting sphere timeout)
[INFO] Checking "release_tmo": = 4.0 (Getting release timeout)
[INFO] Checking "open_hand": = open_hand 0.0 0.0 0.0 0.0 0.0  ... (Getting openHand poss)
[INFO] Checking "open_hand": = open_hand 0.0 0.0 0.0 0.0 0.0  ... (Getting openHand poss)
[INFO] Checking "close_hand": = close_hand 20.0 80.0 30.0 20.0 ... (Getting closeHand poss)
[INFO] Checking "close_hand": = close_hand 20.0 80.0 30.0 20.0 ... (Getting closeHand poss)
[INFO] Checking "vels_hand": = vels_hand 20.0 40.0 50.0 50.0  ... (Getting hand vels)
[INFO] Checking "vels_hand": = vels_hand 20.0 40.0 50.0 50.0  ... (Getting hand vels)
```
Or, if the parameters are not found, to print the default value that it will be used:
```
[ERROR] |yarp.os.Property| cannot read from config2.ini
[INFO] Checking "robot": Getting robot name (default icub)
[INFO] Checking "left_arm": Getting left arm use flag (default on)
[INFO] Checking "right_arm": Getting right arm use flag (default on)
[INFO] Checking "torso": Getting torso use flag (default on)
[INFO] Checking "speech": Getting speech use flag (default on)
[INFO] Checking "use_network": Getting network enable (default off)
[INFO] Checking "simulation": Getting simulation enable (default off)
[INFO] Checking "traj_time": Getting trajectory time (default 2.0)
[INFO] Checking "reach_tol": Getting reaching tolerance (default 0.01)
[INFO] Checking "eye": Getting the used eye (default left)
[INFO] Checking "idle_tmo": Getting idle timeout (default 10000000000.0)
[INFO] Checking "thread_period": Getting thread period [ms] (default 20)
[INFO] Checking "grasp_enable": Getting arm grasp mode (default on)
[INFO] Checking "reach_offset": Getting reaching offset
[INFO] Checking "grasp_offset": Getting grasping offset
[INFO] Checking "hand_orientation": Getting hand orientation
[INFO] Checking "impedance_velocity_mode": Getting arm impedance-velocity-mode (default off)
[INFO] Checking "impedance_stiffness": Getting joints stiffness
[INFO] Checking "impedance_damping": Getting joints damping
[INFO] Checking "poss": Getting home poss
[ERROR] Missing 'poss' parameter
[INFO] Checking "vels": Getting home vels
[ERROR] Missing 'vels' parameter
[ERROR] Error in parameters section 'home_arm'
[ERROR] |yarp.os.impl.ThreadImpl| A thread failed to start with error code: 0
[INFO] |yarp.os.RFModule| RFModule failed to open.
```

**Comment by pattacini** [comment]
Thank you @randaz81 for doing the test 👍🏻 

>I'm still not 100% sure but I think that the only purpose of that code is to print the values read from the configuration file:

I've also double-checked the code and we should be safe removing it as @randaz81 is right about its purpose.

For now, there's no equivalent functionality that has an easy drop-in replacement as the conf files would need to be refactored to rely on the new way (see https://github.com/robotology/yarp/pull/3059).

All considered, we can proceed with merging.

**Review by pattacini — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @pattacini @randaz81 !

**Pull request merged**
