### PR TITLE
Add support for OpenCV4

### PR DESCRIPTION
**Pull request by Nicogene**
This PR add the support for OpenCV4.

It compiles with opencv 3 and 4.

I have to check if https://github.com/robotology/icub-basic-demos/commit/3088978450517cb064594a939967d65965c47f74 is correct.

I have to test the demoRedBall before merging

**OpenCV 2 is not supported**

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Comment by pattacini** [comment]
CI's failing.

**Review by pattacini — CHANGES_REQUESTED** [review]
Could you check the compilation failures?

**Comment by Nicogene** [comment]
Yes sure :+1:

**Review by pattacini — APPROVED** [review]

**Comment by Nicogene** [comment]
`demoRedBall` successfully tested on `iCubGenova01`.
Awaiting that CI passes then I will merge.

In particular here https://github.com/robotology/icub-basic-demos/pull/21/commits/46cc4c3757aea1dc8e4109ebfd233cf858ca2cc7 I did a minimal porting to cv::Mat, port all the pf3DTracker is a huge task, not necessary to be opencv 4 compatible.

**Pull request merged**
