### PR TITLE
Add conda-based Continuous Integration and fix compilation with Gazebo on Windows installed via conda

### PR DESCRIPTION
**Pull request by traversaro**
Add a simple conda-based CI. The goal is to easily test on Windows/macOS/Linux with all dependencies enabled. This complements the existing CI that instead used apt/homebrew/vcpkg (and compiles robotology dependencies from source).

Furthermore, fix compilation of the library that uses Gazebo in Windows by adding the line:
~~~cmake
target_link_directories(${PROJECT_NAME}-world PRIVATE ${GAZEBO_LIBRARY_DIRS})
~~~

In general `target_link_directories` and `link_directories` commands should not be used in CMake (see the note at the end of https://cmake.org/cmake/help/latest/command/target_link_directories.html), but when linking Gazebo (and `Gazebo_LIBRARIES`) this is unfortunately necessary due to many libraries that are provided without full paths, see http://gazebosim.org/tutorials/?tut=plugins_hello_world .

This fixes issue https://github.com/robotology/robotology-superbuild/issues/693 .

Similar PRs:
* https://github.com/robotology/yarp-telemetry/pull/124
* https://github.com/dic-iit/bipedal-locomotion-framework/pull/221

### CODE REVIEW

**Comment by traversaro** [comment]
~The main goal is to reproduce and fix https://github.com/robotology/robotology-superbuild/issues/693~ this was reproduced and fixed.

**Review by pattacini — APPROVED** [review]

**Comment by traversaro** [comment]
WIP as I wanted to check if I can reproduce https://github.com/robotology/robotology-superbuild/issues/693 and fix it before merging.

**Comment by traversaro** [comment]
Error reproduced: 
~~~
2021-04-22T15:41:56.5633232Z LINK : fatal error LNK1181: cannot open input file 'OgreBites.lib' [D:\a\icub-basic-demos\icub-basic-demos\build\demoRedBall\demoRedBall-world.vcxproj]
2021-04-22T15:41:56.6591852Z   Building Custom Rule D:/a/icub-basic-demos/icub-basic-demos/demoYoga/CMakeLists.txt
~~~

**Comment by traversaro** [comment]
@Nicogene the PR is now ready for review.

**Comment by traversaro** [comment]
fyi @Tobias-Fischer, you may be happy to know that the good old red ball demo is getting a Conda-based CI. : )

**Comment by Tobias-Fischer** [comment]
How cool is that? Very nice, good work @traversaro :)
Amazing just to see this line and how much pain it will save dozens of people in the future: `mamba install -c robotology yarp icub-main gazebo icub-contrib-common qt opencv`

**Review by Nicogene — APPROVED** [review]

**Pull request merged**
